version: '3'
services:
  web-scrapper:
    volumes:
      - .././:/app
      - /app/node_modules
    env_file:
      - ../.env.development
    command: npm run dev
  nginx:
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro